spring.application.name=germanMailer

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail.to=${RECIPIENT_EMAIL}

gemini.api.key=${GEMINI_API_KEY}
gemini.models=gemini-3.8-flash,gemini-3.6-flash,gemini-3.5-flash-lite

spring.main.web-application-type=none
